name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Node Backend CI
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./netflix-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # React Frontend CI
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./netflix-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --  --passWithNoTests

      - name: Build frontend
        run: npm run build

  # Deploy (optional)
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Deploy backend (replace with your deployment steps)
        run: |
          # deployment commands for the backend
      - name: Deploy frontend (replace with your deployment steps)
        run: |
          # deployment commands for the frontend
